name: Build MinimalLinux

on:
  release:
    types: [published]

jobs:

  build-dist:

    runs-on: ubuntu-latest

    steps:

    #--------------------------------------------collect--------------------------------------------
    - uses: actions/checkout@v4
    
    - name: Get infomations
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        echo "tag=$tag" >> $GITHUB_ENV
        echo "pkgname=minimal-linux-$tag" >> $GITHUB_ENV
        echo "srcdir=$(pwd)" >> $GITHUB_ENV
        
    #--------------------------------------------build--------------------------------------------
    - name: Build tarball
      run: |
        sudo make -f Makefile.devel dist
    
    - name: Sum md5
      run: |
        sudo sha256sum ${{ env.pkgname }}.tar.xz > ${{ env.pkgname }}.tar.xz.sha256
    
    #--------------------------------------------publish--------------------------------------------

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ env.tag }}
          files: |
            ${{ env.pkgname }}.tar.xz
            ${{ env.pkgname }}.tar.xz.sha256


  build-diskimage:
  
    needs: build-dist
    
    runs-on: ubuntu-latest
    
    steps:
    
    #--------------------------------------------collect--------------------------------------------
    - name: Get infomations
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        echo "tag=$tag" >> $GITHUB_ENV
        echo "pkgname=minimal-linux-$tag" >> $GITHUB_ENV
        echo "srcdir=$(pwd)" >> $GITHUB_ENV

    - name: Collect dependencies
      run: |
        sudo apt-get update
        sudo apt-get install gcc xz-utils gawk grub2 make grep kpartx qemu-utils sed util-linux wget -y
        sudo apt-get install binutils libelf-dev libssl-dev bc flex bison -y
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.4

    - name: Get source distribution tarball
      run: |
        sudo wget https://github.com/${{ github.repository }}/releases/download/${{ env.tag }}/${{ env.pkgname }}.tar.xz
        sudo tar xvf ${{ env.pkgname }}.tar.xz
        sudo mv ${{ env.pkgname }}/* .
    
    #--------------------------------------------build--------------------------------------------
    
    - name: Build binary distribution
      run: |
        sudo ./configure
        sudo make graphic -j$(nproc)
    
    - name: Make packages
      run: |
        sudo sha256sum disk.img.xz > disk.img.xz.sha256
    
    #--------------------------------------------publish--------------------------------------------

    - name: Create release and upload assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.tag }}
        files: |
          disk.img.xz
          disk.img.xz.sha256
          *.png
